name: CI

on:
  push:
    branches: [ main, phase3, "release/*" ]
  pull_request:
    branches: [ main, phase3 ]

jobs:
  backend:
    name: Backend - Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Install backend deps
        working-directory: backend
        run: |
          uv pip install -r requirements.txt

      - name: Run backend tests
        working-directory: backend
        run: |
          uv run pytest -q

  frontend:
    name: Frontend - Typecheck & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci --no-audit --no-fund

      - name: Typecheck
        working-directory: frontend
        run: npx tsc -b --pretty false

      - name: Build
        working-directory: frontend
        env:
          VITE_API_URL: http://localhost:8001
          VITE_POCKETBASE_URL: http://localhost:8090
        run: npm run build --silent

name: CI

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          cd backend
          uv pip install --system -e .[dev]
          cd ..
      - name: Check formatting
        run: ruff format --check .
      - name: Run ruff
        run: ruff check .
      - name: Run tests
        run: pytest -q
