name: CI

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          cd backend
          uv pip install --system -e .[dev]
          cd ..
      - name: Check formatting
        run: ruff format --check .
      - name: Run ruff
        run: ruff check .
      - name: Run tests
        run: pytest -q
